from mistcli.apis.orgs import admins
from mistcli.apis.orgs import alarmtemplates
from mistcli.apis.orgs import assetfilters
from mistcli.apis.orgs import deviceprofiles
from mistcli.apis.orgs import evpn_topologies
from mistcli.apis.orgs import gatewaytemplates
from mistcli.apis.orgs import hubprofiles
from mistcli.apis.orgs import info
from mistcli.apis.orgs import inventory
from mistcli.apis.orgs import licenses
from mistcli.apis.orgs import mxclusters
from mistcli.apis.orgs import mxedges
from mistcli.apis.orgs import mxtunnels
from mistcli.apis.orgs import networks
from mistcli.apis.orgs import networktemplates
from mistcli.apis.orgs import psks
from mistcli.apis.orgs import rftemplates
from mistcli.apis.orgs import secpolicies
from mistcli.apis.orgs import services
from mistcli.apis.orgs import settings
from mistcli.apis.orgs import sitegroups
from mistcli.apis.orgs import sites
from mistcli.apis.orgs import ssoroles
from mistcli.apis.orgs import ssos
from mistcli.apis.orgs import stats
from mistcli.apis.orgs import subscriptions
from mistcli.apis.orgs import templates
from mistcli.apis.orgs import vpns
from mistcli.apis.orgs import webhooks
from mistcli.apis.orgs import wlans
from mistcli.apis.orgs import wxrules
from mistcli.apis.orgs import wxtags
from mistcli.apis.orgs import wxtunnels
from mistcli.apis.orgs import orgs